# Generated by Django 3.2.3 on 2021-08-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.SmallIntegerField(choices=[(0, 'small_blind'), (1, 'big_blind')])),
                ('action', models.SmallIntegerField(choices=[(0, 'fold'), (1, 'turn'), (2, 'raise')])),
                ('current_round', models.SmallIntegerField(choices=[(0, 'pre_flop'), (1, 'flop'), (2, 'turn'), (3, 'river')])),
                ('raise_money', models.IntegerField(default=0)),
                ('call_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_seat', models.SmallIntegerField(choices=[(0, 'small_blind'), (1, 'big_blind')], default=0)),
                ('my_card1', models.IntegerField(default=-1)),
                ('my_card2', models.IntegerField(default=-1)),
                ('opp_card1', models.IntegerField(default=-1)),
                ('opp_card2', models.IntegerField(default=-1)),
                ('turn_card', models.IntegerField(default=-1)),
                ('river_card', models.IntegerField(default=-1)),
                ('win_money', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pots', models.IntegerField(default=150)),
                ('action_id', models.IntegerField(default=0)),
                ('current_round', models.SmallIntegerField(choices=[(0, 'pre_flop'), (1, 'flop'), (2, 'turn'), (3, 'river')], default=0)),
                ('bb_wager', models.IntegerField(default=0)),
                ('sb_wager', models.IntegerField(default=0)),
                ('bb_last', models.IntegerField(default=19900)),
                ('sm_last', models.IntegerField(default=19950)),
                ('raise_time', models.IntegerField(default=0)),
                ('min_raise_money', models.IntegerField(default=100)),
            ],
        ),
    ]
