# Generated by Django 3.2.3 on 2021-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='flop_card1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='flop_card2',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='baseinfo',
            name='flop_card3',
            field=models.IntegerField(default=-1),
        ),
    ]
