# Generated by Django 3.2.3 on 2021-08-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0003_auto_20210803_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusrecord',
            old_name='sm_last',
            new_name='sb_last',
        ),
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'fold'), (1, 'call'), (2, 'raise')]),
        ),
    ]
