# Generated by Django 3.2.3 on 2021-08-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0004_auto_20210803_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.SmallIntegerField(choices=[(0, 'fold'), (1, 'call'), (2, 'raise'), (3, 'guopai'), (4, 'allin'), (5, 'betpot')]),
        ),
    ]
