# Generated by Django 2.2.5 on 2021-08-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0005_alter_action_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='baseinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
