# Generated by Django 2.2.5 on 2021-08-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='', max_length=32, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='money',
            field=models.IntegerField(default='', verbose_name='资金'),
        ),
    ]
