# Generated by Django 2.2.5 on 2021-08-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210819_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='title',
            field=models.CharField(default='一贫如洗', max_length=32, verbose_name='称号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='money',
            field=models.IntegerField(default=0, verbose_name='资金'),
        ),
    ]
