# Generated by Django 3.2.3 on 2021-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210819_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='money',
            field=models.IntegerField(default=2000, verbose_name='资金'),
        ),
    ]
